{{- include "hyperfleet-applier.validateValues" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyperfleet-applier.fullname" . }}
  labels:
    {{- include "hyperfleet-applier.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hyperfleet-applier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "hyperfleet-applier.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hyperfleet-applier.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hyperfleet-applier
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "hyperfleet-applier.fullImageName" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["serve", "--config", "/etc/hyperfleet/config.yaml"]
          volumeMounts:
            - name: config
              mountPath: /etc/hyperfleet
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "hyperfleet-applier.fullname" . }}
